[tool.poetry]
name = "game"
version = "0.1.0"
description = ""
authors = ["Ziqian Wang <2779671262@qq.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pgzero = "^1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
